---
deployment:
  tasks:
    - export THEME=/home/nepraptk/public_html/wp-content/themes/nepreneur
    - /usr/bin/rsync -avz --delete --exclude='.git/' --exclude='.gitignore' \
        $REPO_ROOT/ $THEME/
