---
deployment:
  tasks:
    - 'set -e'
    - 'export DEPLOYPATH=/home/nepraptk/public_html/wp-content/themes/nepreneur'
    - '/bin/mkdir -p "$DEPLOYPATH"'
    # copy all non-hidden files/folders from repo root
    - '/bin/cp -r * "$DEPLOYPATH"/'
